.TH LISTDB "8" "September 2011" "listdb" "Maintenance Commands"
.SH NAME
listdb \- lists data structures used by lessfs
.SH SYNOPSIS
.B /usr/sbin/listdb /path_to_config.cfg
.SH DESCRIPTION
.B listdb
lists information about the data structures used by the lessfs filesystem.  Information about the location of those structures is read from the config file, the same one used to create and mount the filesystem.

.SH "SEE ALSO"
.B lessfs
(1)
.B mklessfs
(8)
.SH "NOTES"
This manpage has been created for Debian GNU/Linux.
