.TH MKLESSFS "8" "September 2011" "mklessfs" "Maintenance Commands"
.SH NAME
mklessfs \- Creates a lessfs filesystem
.SH SYNOPSIS
.B /usr/sbin/mklessfs [\-f] \fB\-c\fR /path_to_config.cfg
.SH DESCRIPTION
.B mklessfs
creates the data structures for the lessfs filesystem, with the values specified in the config file.

\fB\-c\fR Path and name of the configuation file

\fB\-f\fR Overwrite existing databases and create directories when needed

\fB\-h\fR Displays this usage message
.SH "SEE ALSO"
.B lessfs
(1)
.SH "NOTES"
This manpage has been created for Debian GNU/Linux.
